### ISSUE TITLE
[FEAT] Add ability to run on multiple files

### ISSUE THREAD

**Issue by WizzyGeek** [WizzyGeek/entropy#2]
Allow the user to supply multiple files and calculate their entropy sequentially

for example
`python3 entropy.py file1.txt file2.txt file3.txt`

**Comment by Khaleelhabeeb** [comment]
This could be improved to support processing multiple files. Each file's entropy would then reflect its own content's randomness and then prints the entropy statistics for each file with a separator (--- File: {filename} ---) for clarity.                                                                i will open a PR with possible solution.
